namespace: sidecar-injector
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml
- nginx-configmap.yaml
images:
- name: sidecar-injector
  newName: k8stage.azurecr.io/kube-sidecar-injector
  newTag: v0.0.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
